/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quotation;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;

import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Kevin
 */
public class inputform extends javax.swing.JFrame {
        QuotationEntities quote = new QuotationEntities();
        List<QuotationEntities> listQuote = new ArrayList<QuotationEntities>();
    public inputform() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txRmaNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txSnno = new javax.swing.JTextField();
        chbsalereturn = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chbm10 = new javax.swing.JCheckBox();
        chbm20 = new javax.swing.JCheckBox();
        chbm30 = new javax.swing.JCheckBox();
        chbm50 = new javax.swing.JCheckBox();
        chbhdd = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txpartno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        chbbox = new javax.swing.JCheckBox();
        chbfoam = new javax.swing.JCheckBox();
        chbpowercord = new javax.swing.JCheckBox();
        chbdvi = new javax.swing.JCheckBox();
        chbkeyboard = new javax.swing.JCheckBox();
        chbcapturecable = new javax.swing.JCheckBox();
        chbtop = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        chbbottom = new javax.swing.JCheckBox();
        chbfront = new javax.swing.JCheckBox();
        chbwarranty = new javax.swing.JCheckBox();
        chbphoto = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txdustcover = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txAmemo = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        chbpass = new javax.swing.JCheckBox();
        chbfail = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txconclusion = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnQuote = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("RMA number:");

        txRmaNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txRmaNoActionPerformed(evt);
            }
        });

        jLabel2.setText("Serial NUmber:");

        txSnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSnnoActionPerformed(evt);
            }
        });

        chbsalereturn.setText("Sale Return");

        jLabel3.setText("Date:");

        txdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txdateActionPerformed(evt);
            }
        });

        jLabel4.setText("Unit Type:");

        chbm10.setText("M10");
        chbm10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbm10ActionPerformed(evt);
            }
        });

        chbm20.setText("M20");
        chbm20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbm20ActionPerformed(evt);
            }
        });

        chbm30.setText("M30");
        chbm30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbm30ActionPerformed(evt);
            }
        });

        chbm50.setText("M50");
        chbm50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbm50ActionPerformed(evt);
            }
        });

        chbhdd.setText("HDD");
        chbhdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbhddActionPerformed(evt);
            }
        });

        jLabel5.setText("Unit Pn:");

        txpartno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpartnoActionPerformed(evt);
            }
        });

        jLabel6.setText("Reception Check(Check box if positive)");

        chbbox.setText("Box");
        chbbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbboxActionPerformed(evt);
            }
        });

        chbfoam.setText("Foam");
        chbfoam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbfoamActionPerformed(evt);
            }
        });

        chbpowercord.setText("Power cord");
        chbpowercord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbpowercordActionPerformed(evt);
            }
        });

        chbdvi.setText("DVI adapter");
        chbdvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbdviActionPerformed(evt);
            }
        });

        chbkeyboard.setText("Keyboard/mouse");
        chbkeyboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbkeyboardActionPerformed(evt);
            }
        });

        chbcapturecable.setText("Video capture card cable");
        chbcapturecable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbcapturecableActionPerformed(evt);
            }
        });

        chbtop.setText("Top");
        chbtop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbtopActionPerformed(evt);
            }
        });

        jLabel7.setText("Chassis scratches:");

        chbbottom.setText("Bottom");
        chbbottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbbottomActionPerformed(evt);
            }
        });

        chbfront.setText("Front (M50)");
        chbfront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbfrontActionPerformed(evt);
            }
        });

        chbwarranty.setText("Warranty Label");
        chbwarranty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbwarrantyActionPerformed(evt);
            }
        });

        chbphoto.setText("photo");
        chbphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbphotoActionPerformed(evt);
            }
        });

        jLabel8.setText("Missing dust cover:");

        txdustcover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txdustcoverActionPerformed(evt);
            }
        });

        jLabel9.setText("Boot Up Test:");

        txAmemo.setColumns(20);
        txAmemo.setRows(5);
        jScrollPane2.setViewportView(txAmemo);

        jLabel10.setText("Memo:");

        chbpass.setText("Pass");
        chbpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbpassActionPerformed(evt);
            }
        });

        chbfail.setText("Fail");
        chbfail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbfailActionPerformed(evt);
            }
        });

        jLabel11.setText("Case conclusion:");

        txconclusion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txconclusionActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnNew.setText("New");

        btnQuote.setText("Quote");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(chbm10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chbm20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chbm30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chbm50)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chbhdd))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chbbox)
                                .addComponent(jLabel6))
                            .addGap(6, 6, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(chbtop)
                                .addComponent(chbbottom)
                                .addComponent(chbfront)
                                .addComponent(chbwarranty)
                                .addComponent(chbphoto)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txdustcover, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbcapturecable)
                            .addComponent(chbkeyboard)
                            .addComponent(chbdvi)
                            .addComponent(chbpowercord)
                            .addComponent(chbfoam)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txRmaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txpartno)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txdate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chbsalereturn)
                                            .addComponent(txSnno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txconclusion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chbpass)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chbfail))
                                    .addComponent(jLabel11))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuote)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txRmaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txSnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbsalereturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txpartno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbm10)
                    .addComponent(chbm20)
                    .addComponent(chbm30)
                    .addComponent(chbm50)
                    .addComponent(chbhdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbbox)
                    .addComponent(chbtop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbfoam)
                    .addComponent(chbbottom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbpowercord)
                    .addComponent(chbfront))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbdvi)
                    .addComponent(chbwarranty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbkeyboard)
                    .addComponent(chbphoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbcapturecable)
                    .addComponent(jLabel8)
                    .addComponent(txdustcover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbpass)
                            .addComponent(chbfail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txconclusion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnNew)
                            .addComponent(btnQuote))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txRmaNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txRmaNoActionPerformed
        
    }//GEN-LAST:event_txRmaNoActionPerformed

    private void txSnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSnnoActionPerformed
        
    }//GEN-LAST:event_txSnnoActionPerformed

    private void txpartnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpartnoActionPerformed
        
    }//GEN-LAST:event_txpartnoActionPerformed

    private void txdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txdateActionPerformed
        
    }//GEN-LAST:event_txdateActionPerformed

    private void chbm10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbm10ActionPerformed
       
    }//GEN-LAST:event_chbm10ActionPerformed

    private void chbm20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbm20ActionPerformed
        
    }//GEN-LAST:event_chbm20ActionPerformed

    private void chbm30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbm30ActionPerformed
        
    }//GEN-LAST:event_chbm30ActionPerformed

    private void chbm50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbm50ActionPerformed
        
    }//GEN-LAST:event_chbm50ActionPerformed

    private void chbhddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbhddActionPerformed
        
    }//GEN-LAST:event_chbhddActionPerformed

    private void chbboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbboxActionPerformed
        
    }//GEN-LAST:event_chbboxActionPerformed

    private void chbfoamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbfoamActionPerformed
       
    }//GEN-LAST:event_chbfoamActionPerformed

    private void chbpowercordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbpowercordActionPerformed
        
    }//GEN-LAST:event_chbpowercordActionPerformed

    private void chbdviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbdviActionPerformed
        
    }//GEN-LAST:event_chbdviActionPerformed

    private void chbkeyboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbkeyboardActionPerformed
       
    }//GEN-LAST:event_chbkeyboardActionPerformed

    private void chbcapturecableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbcapturecableActionPerformed
        
    }//GEN-LAST:event_chbcapturecableActionPerformed

    private void chbtopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbtopActionPerformed
        
    }//GEN-LAST:event_chbtopActionPerformed

    private void chbbottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbbottomActionPerformed
        
    }//GEN-LAST:event_chbbottomActionPerformed

    private void chbfrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbfrontActionPerformed
        
    }//GEN-LAST:event_chbfrontActionPerformed

    private void chbwarrantyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbwarrantyActionPerformed
        
    }//GEN-LAST:event_chbwarrantyActionPerformed

    private void chbphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbphotoActionPerformed
        
    }//GEN-LAST:event_chbphotoActionPerformed

    private void chbpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbpassActionPerformed
        
    }//GEN-LAST:event_chbpassActionPerformed

    private void chbfailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbfailActionPerformed
        
    }//GEN-LAST:event_chbfailActionPerformed

    private void txconclusionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txconclusionActionPerformed
       
    }//GEN-LAST:event_txconclusionActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
       quote.setRMA(txRmaNo.getText());
       quote.setSN(txSnno.getText());
       quote.setPartNo(txpartno.getText());
       quote.setDate(txdate.getText());
       if(chbm10.isSelected()){
       quote.setModel("M10");}
       if(chbm20.isSelected()){
       quote.setModel("M20");}
       if(chbm30.isSelected()){
       quote.setModel("M30");}
       if(chbm50.isSelected()){
       quote.setModel("M50");}
       if(chbhdd.isSelected()){
       quote.setModel("HDD");}
       if(chbbox.isSelected()){
       quote.setBox("ok");}else{
       quote.setBox("n");
       }
       if(chbfoam.isSelected()){
       quote.setFoam("ok");}else{
       quote.setFoam("n");
       }
       if(chbpowercord.isSelected()){
       quote.setPowercord("ok");}
       else{
       quote.setPowercord("n");
       }
       if(chbdvi.isSelected()){
       quote.setDVI("ok");}else{
       quote.setDVI("n");
       }
       if(chbkeyboard.isSelected()){
       quote.setKeyboard("ok");}else{
       quote.setKeyboard("n");
       }
       if(chbcapturecable.isSelected()){
       quote.setVideocable("ok");}else{
       quote.setVideocable("n");
       }
       if(chbtop.isSelected()){
       quote.setTop("y");}
       else{
       quote.setTop("n");
       }
       if(chbbottom.isSelected()){
       quote.setBottom("y");}
       else{
       quote.setBottom("n");
       }
       if(chbfront.isSelected()){
       quote.setFront("y");}else{
       quote.setFront("n");
       }
       
       quote.setWarranty("y");
       quote.setPhoto("y");
//       quote.setPortCover(Double.parseDouble(txdustcover.getText()));
       quote.setBootUpPass("y");
       quote.setBootUpFail("y");
       quote.setConclusion(txconclusion.getText());
       /*
       txRmaNo.setText("");
       txSnno.setText("");
       txpartno.setText("");
       txdate.setText("");
       chbm10.setSelected(false);*/
       listQuote.add(quote);
       WriteJframeatoExcelFile formwriter = new WriteJframeatoExcelFile();
       String fileName = "C:/Users/Kevin/Desktop/visualizecheck.xlsx";
        try {
           FileInputStream fis = new FileInputStream(fileName);           
           Workbook wb = new XSSFWorkbook(fis);
           Sheet sheet = wb.getSheetAt(0);
           
           int numberOfRow = sheet.getPhysicalNumberOfRows()+1;
           formwriter.writeJframetoFile(fileName, listQuote,numberOfRow);
           
        } catch (FileNotFoundException ex) {
            Logger.getLogger(inputform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(inputform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(inputform.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txdustcoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txdustcoverActionPerformed

    }//GEN-LAST:event_txdustcoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnQuote;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chbbottom;
    private javax.swing.JCheckBox chbbox;
    private javax.swing.JCheckBox chbcapturecable;
    private javax.swing.JCheckBox chbdvi;
    private javax.swing.JCheckBox chbfail;
    private javax.swing.JCheckBox chbfoam;
    private javax.swing.JCheckBox chbfront;
    private javax.swing.JCheckBox chbhdd;
    private javax.swing.JCheckBox chbkeyboard;
    private javax.swing.JCheckBox chbm10;
    private javax.swing.JCheckBox chbm20;
    private javax.swing.JCheckBox chbm30;
    private javax.swing.JCheckBox chbm50;
    private javax.swing.JCheckBox chbpass;
    private javax.swing.JCheckBox chbphoto;
    private javax.swing.JCheckBox chbpowercord;
    private javax.swing.JCheckBox chbsalereturn;
    private javax.swing.JCheckBox chbtop;
    private javax.swing.JCheckBox chbwarranty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txAmemo;
    private javax.swing.JTextField txRmaNo;
    private javax.swing.JTextField txSnno;
    private javax.swing.JTextField txconclusion;
    private javax.swing.JTextField txdate;
    private javax.swing.JTextField txdustcover;
    private javax.swing.JTextField txpartno;
    // End of variables declaration//GEN-END:variables
}
